[[PulseAudio]]
arch = "aarch64"
git-tree-sha1 = "e8c94a028e443270ecdbff50c0ad42232dfaadb3"
libc = "glibc"
os = "linux"

    [[PulseAudio.download]]
    sha256 = "a1c431f71e9897a7bf2b855d327c0d34a5e52ab5240aa5b6ad8efe6037affcab"
    url = "https://github.com/JuliaBinaryWrappers/PulseAudio_jll.jl/releases/download/PulseAudio-v15.0.0+0/PulseAudio.v15.0.0.aarch64-linux-gnu.tar.gz"
[[PulseAudio]]
arch = "aarch64"
git-tree-sha1 = "92bb787e0b679190773450751008d28daf2e6086"
libc = "musl"
os = "linux"

    [[PulseAudio.download]]
    sha256 = "fba8e3dffacfc939431422ca622949af01591404f15a50e04ddf8b4dd4eb6fad"
    url = "https://github.com/JuliaBinaryWrappers/PulseAudio_jll.jl/releases/download/PulseAudio-v15.0.0+0/PulseAudio.v15.0.0.aarch64-linux-musl.tar.gz"
[[PulseAudio]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f97d21e4eb7a4359b858b9478ec53983828f9421"
libc = "glibc"
os = "linux"

    [[PulseAudio.download]]
    sha256 = "088c8790224e2ae8dde6da44611b50e004e467afaa1e9828b7ae5ad52b75cda1"
    url = "https://github.com/JuliaBinaryWrappers/PulseAudio_jll.jl/releases/download/PulseAudio-v15.0.0+0/PulseAudio.v15.0.0.armv7l-linux-gnueabihf.tar.gz"
[[PulseAudio]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "386bc4cc805270cb63a042e1f4fead8f46534c54"
libc = "musl"
os = "linux"

    [[PulseAudio.download]]
    sha256 = "496c3ec7c15f42f446c142550b37b83e4eb35684a4aa0e5211d325be73f4ca69"
    url = "https://github.com/JuliaBinaryWrappers/PulseAudio_jll.jl/releases/download/PulseAudio-v15.0.0+0/PulseAudio.v15.0.0.armv7l-linux-musleabihf.tar.gz"
[[PulseAudio]]
arch = "i686"
git-tree-sha1 = "13f9fc587abc5f47753be55f9c9f19db93a015e0"
libc = "glibc"
os = "linux"

    [[PulseAudio.download]]
    sha256 = "5f55b6b7552042f154f9e90386c3c99deca9b30eb2575191c8ea2f03db9af30d"
    url = "https://github.com/JuliaBinaryWrappers/PulseAudio_jll.jl/releases/download/PulseAudio-v15.0.0+0/PulseAudio.v15.0.0.i686-linux-gnu.tar.gz"
[[PulseAudio]]
arch = "i686"
git-tree-sha1 = "6bd70dc1f1ba94fc37b4405f9f41a1101621c99f"
libc = "musl"
os = "linux"

    [[PulseAudio.download]]
    sha256 = "59cb587f9abf45f7d7a8c1cc175f8215d369bcd5eea47676a04082bb08d2e4f3"
    url = "https://github.com/JuliaBinaryWrappers/PulseAudio_jll.jl/releases/download/PulseAudio-v15.0.0+0/PulseAudio.v15.0.0.i686-linux-musl.tar.gz"
[[PulseAudio]]
arch = "powerpc64le"
git-tree-sha1 = "79e7ba2c0dd22ce1d74372dab1aeef6865fc519a"
libc = "glibc"
os = "linux"

    [[PulseAudio.download]]
    sha256 = "005f78d2e824378d765a2b56741dfe29dfa0be44c32dc4f5253a2c6670af4703"
    url = "https://github.com/JuliaBinaryWrappers/PulseAudio_jll.jl/releases/download/PulseAudio-v15.0.0+0/PulseAudio.v15.0.0.powerpc64le-linux-gnu.tar.gz"
[[PulseAudio]]
arch = "x86_64"
git-tree-sha1 = "1c75e0b11922d976dd06ea40651ad8f58d2094fc"
libc = "glibc"
os = "linux"

    [[PulseAudio.download]]
    sha256 = "46b8944d239dfd3dcbac14b09bd78c1da7f6d3f468fc237a78c91deec02b7ab3"
    url = "https://github.com/JuliaBinaryWrappers/PulseAudio_jll.jl/releases/download/PulseAudio-v15.0.0+0/PulseAudio.v15.0.0.x86_64-linux-gnu.tar.gz"
[[PulseAudio]]
arch = "x86_64"
git-tree-sha1 = "76045e423970ce84cab4b03d88ebb2ef4dc4ee5f"
libc = "musl"
os = "linux"

    [[PulseAudio.download]]
    sha256 = "f068a80a361a87658fbb8ab7f8198255d4377f1bc5eb96ab1f82d37876fc1d48"
    url = "https://github.com/JuliaBinaryWrappers/PulseAudio_jll.jl/releases/download/PulseAudio-v15.0.0+0/PulseAudio.v15.0.0.x86_64-linux-musl.tar.gz"
