[[PulseAudio]]
arch = "aarch64"
git-tree-sha1 = "6842a596c2b4d0831f2926338a09abf05ca69d7e"
libc = "glibc"
os = "linux"

    [[PulseAudio.download]]
    sha256 = "b7365f0c5060f11edef69719bc016e45a00b82c967c0261db0a5fd5bc3c06884"
    url = "https://github.com/JuliaBinaryWrappers/PulseAudio_jll.jl/releases/download/PulseAudio-v15.0.1+0/PulseAudio.v15.0.1.aarch64-linux-gnu.tar.gz"
[[PulseAudio]]
arch = "aarch64"
git-tree-sha1 = "187103be1ceb59c71f5f0cbf01808056f3ea9956"
libc = "musl"
os = "linux"

    [[PulseAudio.download]]
    sha256 = "e202f18be5ac818236f6b6d44d47dc08ab40e9c1af81d2bfbd3a2bfa72fa0ef2"
    url = "https://github.com/JuliaBinaryWrappers/PulseAudio_jll.jl/releases/download/PulseAudio-v15.0.1+0/PulseAudio.v15.0.1.aarch64-linux-musl.tar.gz"
[[PulseAudio]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1b6b8b90dca8c00aa98dc9325b1cf55809f93fba"
libc = "glibc"
os = "linux"

    [[PulseAudio.download]]
    sha256 = "1075b11b1d0efe2a0e18199f4bff63e9bc2d7cb828b21846e1b3f4b11249e2d4"
    url = "https://github.com/JuliaBinaryWrappers/PulseAudio_jll.jl/releases/download/PulseAudio-v15.0.1+0/PulseAudio.v15.0.1.armv7l-linux-gnueabihf.tar.gz"
[[PulseAudio]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7056a4d0095d248191ece1a17b0f96d42ec4a4df"
libc = "musl"
os = "linux"

    [[PulseAudio.download]]
    sha256 = "4100966eb99fad2e394fc6facd99c1ac58e28a393df395806009ddc084bd974d"
    url = "https://github.com/JuliaBinaryWrappers/PulseAudio_jll.jl/releases/download/PulseAudio-v15.0.1+0/PulseAudio.v15.0.1.armv7l-linux-musleabihf.tar.gz"
[[PulseAudio]]
arch = "i686"
git-tree-sha1 = "62dfe614d33e1c3349bd0cb30ca08d831bb7f93a"
libc = "glibc"
os = "linux"

    [[PulseAudio.download]]
    sha256 = "5006f0aa67c671dbc127b8ba411a0df7122edf9cdb38423149f2ec5d83ba5628"
    url = "https://github.com/JuliaBinaryWrappers/PulseAudio_jll.jl/releases/download/PulseAudio-v15.0.1+0/PulseAudio.v15.0.1.i686-linux-gnu.tar.gz"
[[PulseAudio]]
arch = "i686"
git-tree-sha1 = "24ceadb6030b77e7af445c3e70476b831c45b4b4"
libc = "musl"
os = "linux"

    [[PulseAudio.download]]
    sha256 = "107e9c408208df2de02cbcf0fd358dbec0df00d318cdea79cb53e6758e5a6f81"
    url = "https://github.com/JuliaBinaryWrappers/PulseAudio_jll.jl/releases/download/PulseAudio-v15.0.1+0/PulseAudio.v15.0.1.i686-linux-musl.tar.gz"
[[PulseAudio]]
arch = "powerpc64le"
git-tree-sha1 = "1c4c225553e3010efad22c3a9195a0591fa501ed"
libc = "glibc"
os = "linux"

    [[PulseAudio.download]]
    sha256 = "7385666ad534432b1dd79433f33894303cd1e3f718fcf3f42ec4f039ca262bad"
    url = "https://github.com/JuliaBinaryWrappers/PulseAudio_jll.jl/releases/download/PulseAudio-v15.0.1+0/PulseAudio.v15.0.1.powerpc64le-linux-gnu.tar.gz"
[[PulseAudio]]
arch = "x86_64"
git-tree-sha1 = "d4b056e546bf53a8d95e630978ef5fa1d9758cdf"
libc = "glibc"
os = "linux"

    [[PulseAudio.download]]
    sha256 = "4f65457af5cd7bd65ffb79288bca7499ceb514f6ef5c54f59639b4dc6ea0544f"
    url = "https://github.com/JuliaBinaryWrappers/PulseAudio_jll.jl/releases/download/PulseAudio-v15.0.1+0/PulseAudio.v15.0.1.x86_64-linux-gnu.tar.gz"
[[PulseAudio]]
arch = "x86_64"
git-tree-sha1 = "8ee293ef73122f826ac868ea1980b7da3e2ac1b9"
libc = "musl"
os = "linux"

    [[PulseAudio.download]]
    sha256 = "ca199aa7ff2befc49dca74e621348a6f826d0576add416a5cf117de03bf8b544"
    url = "https://github.com/JuliaBinaryWrappers/PulseAudio_jll.jl/releases/download/PulseAudio-v15.0.1+0/PulseAudio.v15.0.1.x86_64-linux-musl.tar.gz"
