# Autogenerated wrapper script for PulseAudio_jll for armv7l-linux-musleabihf
export libpulse, libpulse_mainloop_glib, libpulse_simple, pacat, pacmd, pactl, pasuspender, pulseaudio

using alsa_jll
using Check_jll
using Dbus_jll
using eudev_jll
using FFTW_jll
using Gdbm_jll
using Gettext_jll
using Glib_jll
using GStreamer_jll
using libsndfile_jll
using libasyncns_jll
using libcap_jll
using Libiconv_jll
using Libtool_jll
using OpenSSL_jll
using ORC_jll
using SBC_jll
using SoXResampler_jll
using SpeexDSP_jll
JLLWrappers.@generate_wrapper_header("PulseAudio")
JLLWrappers.@declare_library_product(libpulse, "libpulse.so.0")
JLLWrappers.@declare_library_product(libpulse_mainloop_glib, "libpulse-mainloop-glib.so.0")
JLLWrappers.@declare_library_product(libpulse_simple, "libpulse-simple.so.0")
JLLWrappers.@declare_executable_product(pacat)
JLLWrappers.@declare_executable_product(pacmd)
JLLWrappers.@declare_executable_product(pactl)
JLLWrappers.@declare_executable_product(pasuspender)
JLLWrappers.@declare_executable_product(pulseaudio)
function __init__()
    JLLWrappers.@generate_init_header(alsa_jll, Check_jll, Dbus_jll, eudev_jll, FFTW_jll, Gdbm_jll, Gettext_jll, Glib_jll, GStreamer_jll, libsndfile_jll, libasyncns_jll, libcap_jll, Libiconv_jll, Libtool_jll, OpenSSL_jll, ORC_jll, SBC_jll, SoXResampler_jll, SpeexDSP_jll)
    JLLWrappers.@init_library_product(
        libpulse,
        "lib/libpulse.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libpulse_mainloop_glib,
        "lib/libpulse-mainloop-glib.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libpulse_simple,
        "lib/libpulse-simple.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        pacat,
        "bin/pacat",
    )

    JLLWrappers.@init_executable_product(
        pacmd,
        "bin/pacmd",
    )

    JLLWrappers.@init_executable_product(
        pactl,
        "bin/pactl",
    )

    JLLWrappers.@init_executable_product(
        pasuspender,
        "bin/pasuspender",
    )

    JLLWrappers.@init_executable_product(
        pulseaudio,
        "bin/pulseaudio",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
