# Autogenerated wrapper script for PulseAudio_jll for i686-linux-musl
export libalsa_util, libbluez5_util, libcli, liboss_util, libprotocol_cli, libprotocol_http, libprotocol_native, libprotocol_simple, libpulse, libpulse_mainloop_glib, libpulse_simple, libpulsecommon, libpulsecore, libpulsedsp, libraop, librtp, module_allow_passthrough, module_alsa_card, module_alsa_sink, module_alsa_source, module_always_sink, module_always_source, module_augment_properties, module_bluetooth_discover, module_bluetooth_policy, module_bluez5_device, module_bluez5_discover, module_card_restore, module_cli, module_cli_protocol_tcp, module_cli_protocol_unix, module_combine, module_combine_sink, module_console_kit, module_dbus_protocol, module_default_device_restore, module_detect, module_device_manager, module_device_restore, module_echo_cancel, module_equalizer_sink, module_filter_apply, module_filter_heuristics, module_hal_detect, module_http_protocol_tcp, module_http_protocol_unix, module_intended_roles, module_ladspa_sink, module_loopback, module_match, module_mmkbd_evdev, module_native_protocol_fd, module_native_protocol_tcp, module_native_protocol_unix, module_null_sink, module_null_source, module_oss, module_pipe_sink, module_pipe_source, module_position_event_sounds, module_raop_sink, module_remap_sink, module_remap_source, module_rescue_streams, module_role_cork, module_role_ducking, module_rtp_recv, module_rtp_send, module_rygel_media_server, module_simple_protocol_tcp, module_simple_protocol_unix, module_sine, module_sine_source, module_stream_restore, module_suspend_on_idle, module_switch_on_connect, module_switch_on_port_available, module_tunnel_sink, module_tunnel_sink_new, module_tunnel_source, module_tunnel_source_new, module_udev_detect, module_virtual_sink, module_virtual_source, module_virtual_surround_sink, module_volume_restore, pacat, pacmd, pactl, pasuspender, pulseaudio

using alsa_jll
using BlueZ_jll
using Check_jll
using Dbus_jll
using eudev_jll
using FFTW_jll
using Gdbm_jll
using Glib_jll
using GStreamer_jll
using libsndfile_jll
using libasyncns_jll
using libcap_jll
using Libiconv_jll
using Libtool_jll
using OpenSSL_jll
using SBC_jll
using SoXResampler_jll
using SpeexDSP_jll
JLLWrappers.@generate_wrapper_header("PulseAudio")
JLLWrappers.@declare_library_product(libalsa_util, "libalsa-util.so")
JLLWrappers.@declare_library_product(libbluez5_util, "libbluez5-util.so")
JLLWrappers.@declare_library_product(libcli, "libcli.so")
JLLWrappers.@declare_library_product(liboss_util, "liboss-util.so")
JLLWrappers.@declare_library_product(libprotocol_cli, "libprotocol-cli.so")
JLLWrappers.@declare_library_product(libprotocol_http, "libprotocol-http.so")
JLLWrappers.@declare_library_product(libprotocol_native, "libprotocol-native.so")
JLLWrappers.@declare_library_product(libprotocol_simple, "libprotocol-simple.so")
JLLWrappers.@declare_library_product(libpulse, "libpulse.so.0")
JLLWrappers.@declare_library_product(libpulse_mainloop_glib, "libpulse-mainloop-glib.so.0")
JLLWrappers.@declare_library_product(libpulse_simple, "libpulse-simple.so.0")
JLLWrappers.@declare_library_product(libpulsecommon, "libpulsecommon-15.0.so")
JLLWrappers.@declare_library_product(libpulsecore, "libpulsecore-15.0.so")
JLLWrappers.@declare_library_product(libpulsedsp, "libpulsedsp.so")
JLLWrappers.@declare_library_product(libraop, "libraop.so")
JLLWrappers.@declare_library_product(librtp, "librtp.so")
JLLWrappers.@declare_library_product(module_allow_passthrough, "module-allow-passthrough.so")
JLLWrappers.@declare_library_product(module_alsa_card, "module-alsa-card.so")
JLLWrappers.@declare_library_product(module_alsa_sink, "module-alsa-sink.so")
JLLWrappers.@declare_library_product(module_alsa_source, "module-alsa-source.so")
JLLWrappers.@declare_library_product(module_always_sink, "module-always-sink.so")
JLLWrappers.@declare_library_product(module_always_source, "module-always-source.so")
JLLWrappers.@declare_library_product(module_augment_properties, "module-augment-properties.so")
JLLWrappers.@declare_library_product(module_bluetooth_discover, "module-bluetooth-discover.so")
JLLWrappers.@declare_library_product(module_bluetooth_policy, "module-bluetooth-policy.so")
JLLWrappers.@declare_library_product(module_bluez5_device, "module-bluez5-device.so")
JLLWrappers.@declare_library_product(module_bluez5_discover, "module-bluez5-discover.so")
JLLWrappers.@declare_library_product(module_card_restore, "module-card-restore.so")
JLLWrappers.@declare_library_product(module_cli, "module-cli.so")
JLLWrappers.@declare_library_product(module_cli_protocol_tcp, "module-cli-protocol-tcp.so")
JLLWrappers.@declare_library_product(module_cli_protocol_unix, "module-cli-protocol-unix.so")
JLLWrappers.@declare_library_product(module_combine, "module-combine.so")
JLLWrappers.@declare_library_product(module_combine_sink, "module-combine-sink.so")
JLLWrappers.@declare_library_product(module_console_kit, "module-console-kit.so")
JLLWrappers.@declare_library_product(module_dbus_protocol, "module-dbus-protocol.so")
JLLWrappers.@declare_library_product(module_default_device_restore, "module-default-device-restore.so")
JLLWrappers.@declare_library_product(module_detect, "module-detect.so")
JLLWrappers.@declare_library_product(module_device_manager, "module-device-manager.so")
JLLWrappers.@declare_library_product(module_device_restore, "module-device-restore.so")
JLLWrappers.@declare_library_product(module_echo_cancel, "module-echo-cancel.so")
JLLWrappers.@declare_library_product(module_equalizer_sink, "module-equalizer-sink.so")
JLLWrappers.@declare_library_product(module_filter_apply, "module-filter-apply.so")
JLLWrappers.@declare_library_product(module_filter_heuristics, "module-filter-heuristics.so")
JLLWrappers.@declare_library_product(module_hal_detect, "module-hal-detect.so")
JLLWrappers.@declare_library_product(module_http_protocol_tcp, "module-http-protocol-tcp.so")
JLLWrappers.@declare_library_product(module_http_protocol_unix, "module-http-protocol-unix.so")
JLLWrappers.@declare_library_product(module_intended_roles, "module-intended-roles.so")
JLLWrappers.@declare_library_product(module_ladspa_sink, "module-ladspa-sink.so")
JLLWrappers.@declare_library_product(module_loopback, "module-loopback.so")
JLLWrappers.@declare_library_product(module_match, "module-match.so")
JLLWrappers.@declare_library_product(module_mmkbd_evdev, "module-mmkbd-evdev.so")
JLLWrappers.@declare_library_product(module_native_protocol_fd, "module-native-protocol-fd.so")
JLLWrappers.@declare_library_product(module_native_protocol_tcp, "module-native-protocol-tcp.so")
JLLWrappers.@declare_library_product(module_native_protocol_unix, "module-native-protocol-unix.so")
JLLWrappers.@declare_library_product(module_null_sink, "module-null-sink.so")
JLLWrappers.@declare_library_product(module_null_source, "module-null-source.so")
JLLWrappers.@declare_library_product(module_oss, "module-oss.so")
JLLWrappers.@declare_library_product(module_pipe_sink, "module-pipe-sink.so")
JLLWrappers.@declare_library_product(module_pipe_source, "module-pipe-source.so")
JLLWrappers.@declare_library_product(module_position_event_sounds, "module-position-event-sounds.so")
JLLWrappers.@declare_library_product(module_raop_sink, "module-raop-sink.so")
JLLWrappers.@declare_library_product(module_remap_sink, "module-remap-sink.so")
JLLWrappers.@declare_library_product(module_remap_source, "module-remap-source.so")
JLLWrappers.@declare_library_product(module_rescue_streams, "module-rescue-streams.so")
JLLWrappers.@declare_library_product(module_role_cork, "module-role-cork.so")
JLLWrappers.@declare_library_product(module_role_ducking, "module-role-ducking.so")
JLLWrappers.@declare_library_product(module_rtp_recv, "module-rtp-recv.so")
JLLWrappers.@declare_library_product(module_rtp_send, "module-rtp-send.so")
JLLWrappers.@declare_library_product(module_rygel_media_server, "module-rygel-media-server.so")
JLLWrappers.@declare_library_product(module_simple_protocol_tcp, "module-simple-protocol-tcp.so")
JLLWrappers.@declare_library_product(module_simple_protocol_unix, "module-simple-protocol-unix.so")
JLLWrappers.@declare_library_product(module_sine, "module-sine.so")
JLLWrappers.@declare_library_product(module_sine_source, "module-sine-source.so")
JLLWrappers.@declare_library_product(module_stream_restore, "module-stream-restore.so")
JLLWrappers.@declare_library_product(module_suspend_on_idle, "module-suspend-on-idle.so")
JLLWrappers.@declare_library_product(module_switch_on_connect, "module-switch-on-connect.so")
JLLWrappers.@declare_library_product(module_switch_on_port_available, "module-switch-on-port-available.so")
JLLWrappers.@declare_library_product(module_tunnel_sink, "module-tunnel-sink.so")
JLLWrappers.@declare_library_product(module_tunnel_sink_new, "module-tunnel-sink-new.so")
JLLWrappers.@declare_library_product(module_tunnel_source, "module-tunnel-source.so")
JLLWrappers.@declare_library_product(module_tunnel_source_new, "module-tunnel-source-new.so")
JLLWrappers.@declare_library_product(module_udev_detect, "module-udev-detect.so")
JLLWrappers.@declare_library_product(module_virtual_sink, "module-virtual-sink.so")
JLLWrappers.@declare_library_product(module_virtual_source, "module-virtual-source.so")
JLLWrappers.@declare_library_product(module_virtual_surround_sink, "module-virtual-surround-sink.so")
JLLWrappers.@declare_library_product(module_volume_restore, "module-volume-restore.so")
JLLWrappers.@declare_executable_product(pacat)
JLLWrappers.@declare_executable_product(pacmd)
JLLWrappers.@declare_executable_product(pactl)
JLLWrappers.@declare_executable_product(pasuspender)
JLLWrappers.@declare_executable_product(pulseaudio)
function __init__()
    JLLWrappers.@generate_init_header(alsa_jll, BlueZ_jll, Check_jll, Dbus_jll, eudev_jll, FFTW_jll, Gdbm_jll, Glib_jll, GStreamer_jll, libsndfile_jll, libasyncns_jll, libcap_jll, Libiconv_jll, Libtool_jll, OpenSSL_jll, SBC_jll, SoXResampler_jll, SpeexDSP_jll)
    JLLWrappers.@init_library_product(
        libalsa_util,
        "lib/pulse-15.0/modules/libalsa-util.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libbluez5_util,
        "lib/pulse-15.0/modules/libbluez5-util.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcli,
        "lib/pulse-15.0/modules/libcli.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        liboss_util,
        "lib/pulse-15.0/modules/liboss-util.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libprotocol_cli,
        "lib/pulse-15.0/modules/libprotocol-cli.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libprotocol_http,
        "lib/pulse-15.0/modules/libprotocol-http.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libprotocol_native,
        "lib/pulse-15.0/modules/libprotocol-native.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libprotocol_simple,
        "lib/pulse-15.0/modules/libprotocol-simple.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libpulse,
        "lib/libpulse.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libpulse_mainloop_glib,
        "lib/libpulse-mainloop-glib.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libpulse_simple,
        "lib/libpulse-simple.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libpulsecommon,
        "lib/pulseaudio/libpulsecommon-15.0.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libpulsecore,
        "lib/pulseaudio/libpulsecore-15.0.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libpulsedsp,
        "lib/pulseaudio/libpulsedsp.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libraop,
        "lib/pulse-15.0/modules/libraop.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        librtp,
        "lib/pulse-15.0/modules/librtp.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_allow_passthrough,
        "lib/pulse-15.0/modules/module-allow-passthrough.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_alsa_card,
        "lib/pulse-15.0/modules/module-alsa-card.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_alsa_sink,
        "lib/pulse-15.0/modules/module-alsa-sink.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_alsa_source,
        "lib/pulse-15.0/modules/module-alsa-source.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_always_sink,
        "lib/pulse-15.0/modules/module-always-sink.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_always_source,
        "lib/pulse-15.0/modules/module-always-source.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_augment_properties,
        "lib/pulse-15.0/modules/module-augment-properties.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_bluetooth_discover,
        "lib/pulse-15.0/modules/module-bluetooth-discover.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_bluetooth_policy,
        "lib/pulse-15.0/modules/module-bluetooth-policy.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_bluez5_device,
        "lib/pulse-15.0/modules/module-bluez5-device.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_bluez5_discover,
        "lib/pulse-15.0/modules/module-bluez5-discover.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_card_restore,
        "lib/pulse-15.0/modules/module-card-restore.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_cli,
        "lib/pulse-15.0/modules/module-cli.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_cli_protocol_tcp,
        "lib/pulse-15.0/modules/module-cli-protocol-tcp.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_cli_protocol_unix,
        "lib/pulse-15.0/modules/module-cli-protocol-unix.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_combine,
        "lib/pulse-15.0/modules/module-combine.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_combine_sink,
        "lib/pulse-15.0/modules/module-combine-sink.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_console_kit,
        "lib/pulse-15.0/modules/module-console-kit.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_dbus_protocol,
        "lib/pulse-15.0/modules/module-dbus-protocol.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_default_device_restore,
        "lib/pulse-15.0/modules/module-default-device-restore.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_detect,
        "lib/pulse-15.0/modules/module-detect.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_device_manager,
        "lib/pulse-15.0/modules/module-device-manager.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_device_restore,
        "lib/pulse-15.0/modules/module-device-restore.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_echo_cancel,
        "lib/pulse-15.0/modules/module-echo-cancel.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_equalizer_sink,
        "lib/pulse-15.0/modules/module-equalizer-sink.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_filter_apply,
        "lib/pulse-15.0/modules/module-filter-apply.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_filter_heuristics,
        "lib/pulse-15.0/modules/module-filter-heuristics.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_hal_detect,
        "lib/pulse-15.0/modules/module-hal-detect.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_http_protocol_tcp,
        "lib/pulse-15.0/modules/module-http-protocol-tcp.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_http_protocol_unix,
        "lib/pulse-15.0/modules/module-http-protocol-unix.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_intended_roles,
        "lib/pulse-15.0/modules/module-intended-roles.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_ladspa_sink,
        "lib/pulse-15.0/modules/module-ladspa-sink.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_loopback,
        "lib/pulse-15.0/modules/module-loopback.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_match,
        "lib/pulse-15.0/modules/module-match.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_mmkbd_evdev,
        "lib/pulse-15.0/modules/module-mmkbd-evdev.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_native_protocol_fd,
        "lib/pulse-15.0/modules/module-native-protocol-fd.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_native_protocol_tcp,
        "lib/pulse-15.0/modules/module-native-protocol-tcp.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_native_protocol_unix,
        "lib/pulse-15.0/modules/module-native-protocol-unix.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_null_sink,
        "lib/pulse-15.0/modules/module-null-sink.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_null_source,
        "lib/pulse-15.0/modules/module-null-source.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_oss,
        "lib/pulse-15.0/modules/module-oss.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_pipe_sink,
        "lib/pulse-15.0/modules/module-pipe-sink.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_pipe_source,
        "lib/pulse-15.0/modules/module-pipe-source.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_position_event_sounds,
        "lib/pulse-15.0/modules/module-position-event-sounds.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_raop_sink,
        "lib/pulse-15.0/modules/module-raop-sink.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_remap_sink,
        "lib/pulse-15.0/modules/module-remap-sink.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_remap_source,
        "lib/pulse-15.0/modules/module-remap-source.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_rescue_streams,
        "lib/pulse-15.0/modules/module-rescue-streams.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_role_cork,
        "lib/pulse-15.0/modules/module-role-cork.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_role_ducking,
        "lib/pulse-15.0/modules/module-role-ducking.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_rtp_recv,
        "lib/pulse-15.0/modules/module-rtp-recv.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_rtp_send,
        "lib/pulse-15.0/modules/module-rtp-send.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_rygel_media_server,
        "lib/pulse-15.0/modules/module-rygel-media-server.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_simple_protocol_tcp,
        "lib/pulse-15.0/modules/module-simple-protocol-tcp.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_simple_protocol_unix,
        "lib/pulse-15.0/modules/module-simple-protocol-unix.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_sine,
        "lib/pulse-15.0/modules/module-sine.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_sine_source,
        "lib/pulse-15.0/modules/module-sine-source.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_stream_restore,
        "lib/pulse-15.0/modules/module-stream-restore.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_suspend_on_idle,
        "lib/pulse-15.0/modules/module-suspend-on-idle.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_switch_on_connect,
        "lib/pulse-15.0/modules/module-switch-on-connect.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_switch_on_port_available,
        "lib/pulse-15.0/modules/module-switch-on-port-available.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_tunnel_sink,
        "lib/pulse-15.0/modules/module-tunnel-sink.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_tunnel_sink_new,
        "lib/pulse-15.0/modules/module-tunnel-sink-new.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_tunnel_source,
        "lib/pulse-15.0/modules/module-tunnel-source.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_tunnel_source_new,
        "lib/pulse-15.0/modules/module-tunnel-source-new.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_udev_detect,
        "lib/pulse-15.0/modules/module-udev-detect.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_virtual_sink,
        "lib/pulse-15.0/modules/module-virtual-sink.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_virtual_source,
        "lib/pulse-15.0/modules/module-virtual-source.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_virtual_surround_sink,
        "lib/pulse-15.0/modules/module-virtual-surround-sink.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        module_volume_restore,
        "lib/pulse-15.0/modules/module-volume-restore.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        pacat,
        "bin/pacat",
    )

    JLLWrappers.@init_executable_product(
        pacmd,
        "bin/pacmd",
    )

    JLLWrappers.@init_executable_product(
        pactl,
        "bin/pactl",
    )

    JLLWrappers.@init_executable_product(
        pasuspender,
        "bin/pasuspender",
    )

    JLLWrappers.@init_executable_product(
        pulseaudio,
        "bin/pulseaudio",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
